<?xml version="1.0"?>
<package format="3">
  <name>udp_h264_camera</name>
  <version>0.0.1</version>
  <description>UDP H264 camera ROS2 node</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>